---
- name: Mitigate SSH brute force attack
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Block the offending IP address using iptables
      become: true
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked SSH brute force attack from 192.168.1.4"
        state: present
        direction: INPUT
        table: filter
      when: "'192.168.1.2' in ansible_host"
