---
- name: Mitigate DNS Exfiltration on lubh1
  hosts: lubh1
  become: true
  tasks:
    - name: Block specific malicious DNS query by adding to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 q7qlfqepuwi6816ol1rknt1glurrsm.kmwj9ib4yl1mxt4sfrdn322c30yazj.9kvdspo8kpnsf8qv2kuxxxxo7tfp97.malicious.server"
        create: true
        owner: root
        group: root
        mode: '0644'
        state: present
        insertafter: EOF
        backup: true

- name: Prevent future DNS Exfiltration attempts on router
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add firewall rules to drop DNS queries for malicious.server from lubh1
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward protocol=udp dst-port=53 src-address=192.168.1.2 content="malicious.server" action=drop comment="Drop DNS exfiltration from lubh1"
          - /ip firewall filter add chain=forward protocol=tcp dst-port=53 src-address=192.168.1.2 content="malicious.server" action=drop comment="Drop DNS exfiltration from lubh1"