---
- name: Mitigate SSH Brute Force Attack
  hosts: lubh3
  become: true
  tasks:
    - name: Block the IP address using iptables
      community.general.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked IP due to SSH brute force attack"
        state: present
      register: iptables_result

    - name: Save iptables rules (if changed)
      command: iptables-save
      when: iptables_result.changed
    
- name: Block IP on firewall via Mikrotik
  hosts: Mikrotik01
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Login to Mikrotik
      routeros_command:
        commands:
          - /ip/firewall/filter/add chain=forward src-address=192.168.1.4 action=drop comment="SSH Brute Force Mitigation"
