- name: Mitigate SSH brute force attack
  hosts: lubh1
  become: yes
  tasks:
    - name: Block attacker IP address via iptables
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.1.4
        jump: DROP
        state: present
        comment: "Blocked due to SSH brute-force attack from Wazuh alert"