- name: Mitigate SSH Brute Force Attack
  hosts: lubh1
  become: yes
  tasks:
    - name: Block suspicious IP for SSH brute force
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.56.1
        jump: DROP
        state: present