---
- name: Mitigate SSH Brute Force Attack
  hosts: lubh3
  become: true
  tasks:
    - name: Block the attacking IP address using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked SSH brute force attacker"
        state: present
        direction: INPUT
