---
- hosts: lubh3
  become: true
  tasks:
    - name: Block SSH access to 192.168.1.2 via iptables
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.1.2
        jump: REJECT
        reject_with: tcp-reset
        state: present
        comment: "Block SSH scan from 192.168.1.2"

- hosts: Mikrotik01
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add a firewall rule to drop traffic from 192.168.1.4 to 192.168.1.2 on port 22
      routeros_command:
        commands:
          - /ip/firewall/filter/add chain=forward src-address=192.168.1.4 dst-address=192.168.1.2 protocol=tcp dst-port=22 action=drop comment="Drop SSH scan from lubh3 to lubh1"
