---
- name: Mitigate SSH brute force attack
  hosts: lubh1
  become: true
  tasks:
    - name: Block the offending IP address using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ ansible_facts.default_ipv4.gateway }}"
        destination: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked IP {{ ansible_facts.default_ipv4.gateway }} due to SSH brute force attempt from 192.168.1.4"
        state: present
        insert: 1
    - name: Block the offending IP address using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked IP 192.168.1.4 due to SSH brute force attempt"
        state: present
        insert: 1
