---
- name: Mitigate SSH Brute Force Attack on Host
  hosts: lubh1
  become: true
  tasks:
    - name: Block the malicious IP address using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.168.56.1
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked IP due to SSH brute force attempt from 192.168.56.1"

- name: Router configuration to block cross-subnet SSH brute force
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add firewall rule to drop SSH traffic from attacker IP to target subnet
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.56.1 dst-address=192.168.1.0/24 dst-port=22 protocol=tcp action=drop comment="Drop SSH brute force from 192.168.56.1 to 192.168.1.0/24"