---
- name: Mitigate SSH Brute Force Attack
  hosts: lubh3
  become: true
  tasks:
    - name: Block the malicious IP address using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked self-referencing IP due to SSH brute force attempt"

- name: Router configuration to restrict outbound SSH from potential attacker host
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add firewall rule to drop SSH traffic from lubh3 to admin subnet
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.1.4 dst-address=192.168.0.0/24 protocol=tcp dst-port=22 action=drop comment="Drop SSH from lubh3 to admin LAN"
    - name: Add firewall rule to drop SSH traffic from lubh3 to host-only subnet
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.1.4 dst-address=192.168.56.0/24 protocol=tcp dst-port=22 action=drop comment="Drop SSH from lubh3 to host-only LAN"