---
- name: Mitigate SSH Brute Force Attack
  hosts: lubh1
  become: true
  tasks:
    - name: Block the offending IP address using iptables
      community.general.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked IP due to SSH brute force attack"
        state: present
      register: iptables_result

    - name: Save iptables rules (if changed)
      become: true
      shell: "iptables-save"
      args:
        executable: /bin/bash
      when: iptables_result.changed

- name: Mitigate SSH Brute Force Attack - Mikrotik
  hosts: Mikrotik01
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Add IP address to address list
      community.routeros.routeros_command:
        commands:
          - /ip/firewall/address-list/add address=192.168.1.4 list=ssh_blacklist comment="SSH brute-force mitigation"

    - name: Add firewall rule to drop traffic from address list
      community.routeros.routeros_command:
        commands:
          - /ip/firewall/filter/add chain=forward src-address-list=ssh_blacklist protocol=tcp dst-port=22 action=drop comment="Drop SSH brute-force traffic"
      ignore_errors: true

    - name: Add firewall rule to drop traffic to address list
      community.routeros.routeros_command:
        commands:
          - /ip/firewall/filter/add chain=input src-address-list=ssh_blacklist protocol=tcp dst-port=22 action=drop comment="Drop SSH brute-force traffic to router"
      ignore_errors: true
