---
- name: Mitigate C2 Communication from Endpoint
  hosts: lubh1
  become: true
  tasks:
    - name: Block outbound C2 communication to known C2 IP (100.68.52.65:80)
      ansible.builtin.iptables:
        chain: OUTPUT
        destination: 100.68.52.65
        destination_port: 80
        protocol: tcp
        jump: DROP
        comment: "Blocked C2 traffic to 100.68.52.65:80 detected by Suricata"

- name: Network-wide Prevention of C2 Communication
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add firewall rule on router to drop all traffic to known C2 IP (100.68.52.65:80)
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward dst-address=100.68.52.65 protocol=tcp dst-port=80 action=drop comment="Drop C2 traffic to 100.68.52.65 detected by Suricata"