---
- name: Mitigate SSH Brute Force Attack from 192.168.1.4
  hosts: lubh1
  become: true
  tasks:
    - name: Block IP address 192.168.1.4 using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked SSH brute force attack from 192.168.1.4"
        state: present
        direction: INPUT
        out_interface: "{{ ansible_default_ipv4.interface }}"
