- name: Mitigate SSH brute force attack
  hosts: lubh1
  become: yes
  tasks:
    - name: Block attacker IP 192.168.1.4 for SSH attempts on lubh1
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.1.4
        jump: DROP
        state: present
        comment: "Blocked SSH brute force from 192.168.1.4"