---
- name: Mitigate SSH Brute Force Attack
  hosts: lubh1
  gather_facts: false
  tasks:
    - name: Block IP address of attacker
      become: true
      iptables:
        chain: INPUT
        source: 192.168.56.1
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked SSH brute force attacker"
        state: present
    - name: Ensure IP address is blocked (IPv6)
      become: true
      iptables:
        chain: INPUT
        source: 192.168.56.1
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked SSH brute force attacker"
        state: present
        ip_version: ipv6
- name: Mitigate SSH Brute Force Attack
  hosts: Mikrotik01
  gather_facts: false
  tasks:
    - name: Add IP address to address list
      community.routeros.routeros_command:
        commands:
          - /ip/firewall/address-list/add address=192.168.56.1 list=ssh_blacklist comment="Added by Ansible due to SSH brute force"
    - name: Apply rule to block ssh traffic
      community.routeros.routeros_command:
        commands:
          - /ip/firewall/filter/add chain=forward src-address-list=ssh_blacklist protocol=tcp dst-port=22 action=drop comment="Drop SSH brute force traffic"
