---
- name: Mitigate C2 communication on affected host
  hosts: lubh1
  become: true
  tasks:
    - name: Block outbound traffic to known C2 IP via iptables
      ansible.builtin.iptables:
        chain: OUTPUT
        destination: 103.207.85.8
        jump: DROP
        comment: "Blocked outbound C2 communication to 103.207.85.8"

- name: Prevent future C2 communication across the network via router
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add firewall rule to drop traffic to known C2 IP
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward dst-address=103.207.85.8 action=drop comment="Drop traffic to known C2 IP 103.207.85.8"