---
- hosts: lubh3
  become: true
  tasks:
    - name: Block the suspicious IP address using iptables
      iptables:
        chain: INPUT
        source: 192.168.1.2
        jump: DROP
        comment: "Blocked SSH scan attempt from 192.168.1.2"
        state: present
        protocol: tcp

- hosts: ansible-server
  tasks:
    - name: Block the attacker IP on the firewall
      community.routeros.routeros_command:
        commands:
          - /ip/firewall/filter/add chain=forward src-address=192.168.1.2 action=drop comment="Drop SSH scanning from 192.168.1.2"
