---
- name: Verify SSH Brute Force Mitigation
  hosts: lubh1
  become: true
  tasks:
    - name: Check if iptables rule exists
      iptables:
        chain: INPUT
        source: 192.168.56.1
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked IP due to SSH brute force attempt"
        state: present
      check_mode: true
      register: iptables_check_result

    - name: Report iptables rule check result
      debug:
        msg: "Iptables rule check: {{ 'Passed' if iptables_check_result.check_mode else 'Failed' }}"

    - name: Check syslog for block confirmation
      shell: grep "Blocked IP 192.168.56.1 due to SSH brute force attempt" /var/log/syslog || true
      register: syslog_check_result
      ignore_errors: true

    - name: Report syslog check result
      debug:
        msg: "Syslog entry check: {{ 'Passed' if syslog_check_result.rc == 0 else 'Failed' }}"
