---
- name: Mitigate DNS Exfiltration Attack
  hosts: lubh1
  gather_facts: false
  tasks:
    - name: Block DNS queries for potentially exfiltrating domain
      become: true
      blockinfile:
        path: /etc/hosts
        block: |
          127.0.0.1  hola.que.tal.como.estas.que.como.what.que.as.aaaa
        marker: "# {mark} DNS Exfiltration Mitigation"

- name: Mitigate DNS Exfiltration Attack (Firewall)
  hosts: ansible-server
  gather_facts: false
  tasks:
    - name: Block outbound DNS traffic from the affected host (lubh1) to non standard DNS servers
      community.general.microtik_command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.1.2 dst-port=!53 protocol=udp action=drop comment="Mitigate DNS Exfiltration - Block non standard DNS"
      delegate_to: 192.168.0.1
