```yaml
---
- name: Mitigate DNS Exfiltration on compromised host
  hosts: lubh1
  become: true
  tasks:
    - name: Block malicious domain in /etc/hosts to prevent resolution
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 malicious.com"
        insertafter: EOF
        state: present
        create: true

    - name: Ensure all outbound DNS traffic from lubh1 goes only to the legitimate internal DNS server
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 53
        jump: ACCEPT
        destination: 192.168.1.1
        comment: "Allow DNS queries only to internal legitimate DNS server"
        state: present

    - name: Drop all other outbound DNS queries from lubh1 to prevent exfiltration bypass
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 53
        jump: DROP
        comment: "Drop all other outbound DNS queries to prevent exfiltration and bypass"
        state: present

- name: Restrict DNS outgoing traffic on router for 192.168.1.0/24 subnet for future prevention
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add firewall rule to allow DNS from 192.168.1.0/24 to legitimate internal DNS server
      community.routeros.command:
        commands:
          - "/ip firewall filter add chain=forward action=accept protocol=udp dst-port=53 src-address=192.168.1.0/24 dst-address=192.168.1.1 comment=\"Allow DNS from 192.168.1.0/24 to internal DNS server\" place-before=0"

    - name: Add firewall rule to drop non-legitimate DNS traffic from the 192.168.1.0/24 subnet
      community.routeros.command:
        commands:
          - "/ip firewall filter add chain=forward action=drop protocol=udp dst-port=53 src-address=192.168.1.0/24 dst-address=!192.168.1.1 comment=\"Drop non-legitimate DNS from 192.168.1.0/24\""
```