---
- name: Mitigate SSH Brute Force Attack
  hosts: lubh1
  become: true
  tasks:
    - name: Block the malicious IP address using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked IP due to SSH brute force attempt from 192.168.1.4"

- name: Router configuration to prevent future SSH attacks from attacker host
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add firewall rule to drop SSH traffic from attacker's 192.168.1.x IP to admin LAN
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.1.4 dst-address=192.168.0.0/24 protocol=tcp dst-port=22 action=drop comment="Drop SSH from 192.168.1.4 to admin LAN"
    - name: Add firewall rule to drop SSH traffic from attacker's 192.168.1.x IP to management LAN
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.1.4 dst-address=192.168.56.0/24 protocol=tcp dst-port=22 action=drop comment="Drop SSH from 192.168.1.4 to management LAN"
    - name: Add firewall rule to drop SSH traffic from attacker's 192.168.56.x IP to admin LAN
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.56.103 dst-address=192.168.0.0/24 protocol=tcp dst-port=22 action=drop comment="Drop SSH from 192.168.56.103 to admin LAN"
    - name: Add firewall rule to drop SSH traffic from attacker's 192.168.56.x IP to office LAN
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.56.103 dst-address=192.168.1.0/24 protocol=tcp dst-port=22 action=drop comment="Drop SSH from 192.168.56.103 to office LAN"