- name: Mitigate SSH Brute-Force Attack
  hosts: lubh1
  become: yes

  tasks:
    - name: Block incoming SSH connections from source IP 192.168.1.4
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.1.4
        jump: DROP
        state: present
        comment: "Blocked SSH brute-force attempt from 192.168.1.4"