- name: Mitigate SSH Brute Force Attack
  hosts: lubh1
  become: yes
  tasks:
    - name: Block attacker IP for SSH on the target host
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 192.168.56.1
        jump: DROP
        state: present
        comment: "Block SSH brute force from 192.168.56.1 as identified by Wazuh"