---
- name: Mitigate SSH Brute Force Attack
  hosts: lubh1
  become: true
  tasks:
    - name: Block the offending IP address using iptables
      community.general.iptables:
        chain: INPUT
        source: 192.168.56.1
        protocol: tcp
        destination_port: 22
        jump: DROP
        comment: "Blocked IP due to SSH brute force attack"
        state: present
    - name: Block the offending IP address on Mikrotik Router
      community.routeros.routeros_command:
        commands:
          - /ip/firewall/filter/add chain=input src-address=192.168.56.1 protocol=tcp dst-port=22 action=drop comment="Blocked IP due to SSH brute force attack"
      delegate_to: 192.168.0.1
