---
- name: Mitigate Network Scan from workstation
  hosts: lubh3
  become: true
  tasks:
    - name: Block outgoing TCP connections from attacker to scanned target
      ansible.builtin.iptables:
        chain: OUTPUT
        destination: 172.12.0.2
        protocol: tcp
        jump: DROP
        comment: "Blocked outgoing TCP traffic to suspected scan target (SYN Scan Detected)"

- name: Router configuration to block scan traffic
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Check if firewall rule already exists
      community.routeros.command:
        commands:
          - '/ip firewall filter print terse where comment~"Drop SYN scan from workstation to external target"'
      register: firewall_rule_status
      changed_when: false

    - name: Add firewall rule to drop TCP traffic from attacker to scanned target if not present
      community.routeros.command:
        commands:
          - '/ip firewall filter add chain=forward src-address=192.168.1.4 dst-address=172.12.0.2 protocol=tcp action=drop comment="Drop SYN scan from workstation to external target"'
      when: firewall_rule_status.stdout_lines | length == 0