---
- name: Mitigate SYN Scan on Webserver
  hosts: webserver
  become: true
  tasks:
    - name: Block the malicious source IP address using iptables
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.168.1.4
        protocol: tcp
        destination_port: 54001
        jump: DROP
        comment: "Blocked IP due to detected SYN scan"

- name: Router configuration to block SYN scan from source to webserver
  hosts: router1
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Add firewall rule to drop all TCP traffic from the attacker workstation to the webserver
      community.routeros.command:
        commands:
          - /ip firewall filter add chain=forward src-address=192.168.1.4 dst-address=172.12.0.2 protocol=tcp action=drop comment="Drop TCP from lubh3 to webserver due to SYN scan"